name = "smm-api"
main = "src/index.js"
compatibility_date = "2025-08-08"
compatibility_flags = ["nodejs_compat"]

[vars]
# Optional: used in /api/publish later
META_APP_ID = ""
META_APP_SECRET = ""
LINKEDIN_CLIENT_ID = ""
LINKEDIN_CLIENT_SECRET = ""
X_BEARER = ""

[[d1_databases]]
binding = "DB"
database_name = "smm-db"
database_id = "d93fa292-cb4f-49b3-88ed-e413f3b2982b"

[[kv_namespaces]]
binding = "CACHE"
id = "REPLACE_WITH_KV_ID"

[[r2_buckets]]
binding = "R2"
bucket_name = "smm-exports"

[queues.producers]
# optional later for async crawl jobs

[observability]
enabled = true
