name = "smm-api"
main = "src/index.js"
compatibility_date = "2025-08-08"
compatibility_flags = ["nodejs_compat"]

[vars]
META_APP_ID = ""
META_APP_SECRET = ""
LINKEDIN_CLIENT_ID = ""
LINKEDIN_CLIENT_SECRET = ""
X_BEARER = ""

[[d1_databases]]
binding = "DB"
database_name = "smm-db"
database_id = "d93fa292-cb4f-49b3-88ed-e413f3b2982b"   # <- use your actual ID

[[kv_namespaces]]
binding = "CACHE"
id = "f657d570a04545d4b18f1a8818d4166f"

[[r2_buckets]]
binding = "R2"
bucket_name = "smm-exports"

[observability]
enabled = true

# Build the UI in /pages and copy to /public before deploy
[build]
command = """
npm --prefix ./pages ci && \
npm --prefix ./pages run build && \
rm -rf ./public && mkdir -p ./public && \
cp -R ./pages/dist/* ./public/
"""

# Serve static assets from ./public
[assets]
directory = "./public"
html_handling = "auto-trailing-slash"
